from .ups_text_component import UpsTextComponent as UpsTextComponent
from .fps_text_component import FpsTextComponent as FpsTextComponent
# from .player_movement_component import PlayerMovementComponent as PlayerMovementComponent
# from .chunk_map_camera_component import ChunkMapCameraComponent as ChunkMapCameraComponent
